# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
    -   id: forbid-tabs
        exclude: |
          (?x)(
              ^gdb/|
              ^bash/|
          )
- repo: https://github.com/JohnnyMorganz/StyLua
  rev: v0.18.2
  hooks:
    - id: stylua-github
