# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 2000

[directory]
truncation_length = 8

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[battery]
disabled = true

[package]
disabled = true

[docker_context]
disabled = true

[pulumi]
disabled = true
